TYPE=VIEW
query=select `LV`.`visitId` AS `visitId`,`LU`.`userId` AS `userId`,`LV`.`serverTime` AS `serverTime`,`LU`.`visitLastActionTime` AS `visitLastActionTime`,`LV`.`URLId` AS `urlId`,count(`LV`.`URLId`) AS `hits`,`UL`.`title` AS `title`,concat(`UL`.`protocol`,`UL`.`url`) AS `url`,concat(`UL2`.`protocol`,`UL2`.`url`) AS `refUrl`,`LU`.`visitorId` AS `visitorId`,`LU`.`ipAddress` AS `ipAddress`,`LU`.`city` AS `city`,`C`.`alpha2Code` AS `alpha2Code`,`C`.`name` AS `country`,`LU`.`deviceType` AS `deviceType`,`B`.`name` AS `browser`,`OS`.`name` AS `osystem`,`LU`.`latitude` AS `latitude`,`LU`.`longitude` AS `longitude`,`R`.`name` AS `resolution`,`SE`.`name` AS `searchEngine`,`TB`.`name` AS `toolBar` from (((((((((`expwpdb`.`wp_wsm_logVisit` `LV` left join `expwpdb`.`wp_wsm_logUniqueVisit` `LU` on((`LU`.`id` = `LV`.`visitId`))) left join `expwpdb`.`wp_wsm_countries` `C` on((`C`.`id` = `LU`.`countryId`))) left join `expwpdb`.`wp_wsm_browsers` `B` on((`B`.`id` = `LU`.`browserId`))) left join `expwpdb`.`wp_wsm_resolutions` `R` on((`R`.`id` = `LU`.`resolutionId`))) left join `expwpdb`.`wp_wsm_url_log` `UL` on((`LV`.`URLId` = `UL`.`id`))) left join `expwpdb`.`wp_wsm_url_log` `UL2` on((`LV`.`refererUrlId` = `UL2`.`id`))) left join `expwpdb`.`wp_wsm_searchEngines` `SE` on((`SE`.`id` = `UL`.`searchEngine`))) left join `expwpdb`.`wp_wsm_toolBars` `TB` on((`TB`.`id` = `UL`.`toolBar`))) left join `expwpdb`.`wp_wsm_oSystems` `OS` on((`OS`.`id` = `LU`.`oSystemId`))) group by `LV`.`visitId`,`LV`.`URLId` order by `LV`.`visitId` desc,`LV`.`serverTime` desc
md5=6556af50399ee341b7a413b2f00d27a2
updatable=0
algorithm=0
definer_user=expwp_user
definer_host=%
suid=2
with_check_option=0
timestamp=2025-06-06 13:59:21
create-version=1
source=SELECT LV.visitId,LU.userId, LV.serverTime,LU.visitLastActionTime, LV.urlId, COUNT(LV.urlId) as hits, UL.title, CONCAT(UL.protocol, UL.url) as url, CONCAT(UL2.protocol, UL2.url) as refUrl, LU.visitorId, LU.ipAddress,LU.city, C.alpha2Code,C.name as country, LU.deviceType, B.name as browser,OS.name as osystem, LU.latitude, LU.longitude,R.name as resolution, SE.name as searchEngine, TB.name as toolBar FROM wp_wsm_logVisit LV LEFT JOIN wp_wsm_logUniqueVisit LU ON LU.id=LV.visitId LEFT JOIN wp_wsm_countries C ON C.id=LU.countryId LEFT JOIN wp_wsm_browsers B ON B.id=LU.browserId LEFT JOIN wp_wsm_resolutions R ON R.id=LU.resolutionId LEFT JOIN wp_wsm_url_log UL ON LV.urlId=UL.id LEFT JOIN wp_wsm_url_log UL2 ON LV.refererUrlId=UL2.id  LEFT JOIN wp_wsm_searchEngines SE ON SE.id=UL.searchEngine LEFT JOIN wp_wsm_toolBars TB ON TB.id=UL.toolBar LEFT JOIN wp_wsm_oSystems OS ON OS.id=LU.oSystemId GROUP BY LV.visitId,LV.urlId ORDER BY LV.visitId DESC ,LV.serverTime DESC
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_520_ci
view_body_utf8=select `LV`.`visitId` AS `visitId`,`LU`.`userId` AS `userId`,`LV`.`serverTime` AS `serverTime`,`LU`.`visitLastActionTime` AS `visitLastActionTime`,`LV`.`URLId` AS `urlId`,count(`LV`.`URLId`) AS `hits`,`UL`.`title` AS `title`,concat(`UL`.`protocol`,`UL`.`url`) AS `url`,concat(`UL2`.`protocol`,`UL2`.`url`) AS `refUrl`,`LU`.`visitorId` AS `visitorId`,`LU`.`ipAddress` AS `ipAddress`,`LU`.`city` AS `city`,`C`.`alpha2Code` AS `alpha2Code`,`C`.`name` AS `country`,`LU`.`deviceType` AS `deviceType`,`B`.`name` AS `browser`,`OS`.`name` AS `osystem`,`LU`.`latitude` AS `latitude`,`LU`.`longitude` AS `longitude`,`R`.`name` AS `resolution`,`SE`.`name` AS `searchEngine`,`TB`.`name` AS `toolBar` from (((((((((`expwpdb`.`wp_wsm_logVisit` `LV` left join `expwpdb`.`wp_wsm_logUniqueVisit` `LU` on((`LU`.`id` = `LV`.`visitId`))) left join `expwpdb`.`wp_wsm_countries` `C` on((`C`.`id` = `LU`.`countryId`))) left join `expwpdb`.`wp_wsm_browsers` `B` on((`B`.`id` = `LU`.`browserId`))) left join `expwpdb`.`wp_wsm_resolutions` `R` on((`R`.`id` = `LU`.`resolutionId`))) left join `expwpdb`.`wp_wsm_url_log` `UL` on((`LV`.`URLId` = `UL`.`id`))) left join `expwpdb`.`wp_wsm_url_log` `UL2` on((`LV`.`refererUrlId` = `UL2`.`id`))) left join `expwpdb`.`wp_wsm_searchEngines` `SE` on((`SE`.`id` = `UL`.`searchEngine`))) left join `expwpdb`.`wp_wsm_toolBars` `TB` on((`TB`.`id` = `UL`.`toolBar`))) left join `expwpdb`.`wp_wsm_oSystems` `OS` on((`OS`.`id` = `LU`.`oSystemId`))) group by `LV`.`visitId`,`LV`.`URLId` order by `LV`.`visitId` desc,`LV`.`serverTime` desc
